### ISSUE TITLE
EnvironmentSecretsPropertyEnvironmentPostProcessor not working as expected

### ISSUE THREAD

**Issue by Radiergummi** [V1ncNet/secrets-spring-boot#5]
I tried to set up a project to read environment configuration. Using the default combination of all four post processors works, but I cannot get it to accept a `_FILE` variable. 

For a simple compose configuration like this:
```yaml
secrets:
  database-password:
    environment: DATABASE_PASSWORD # assume this is set to "foo"
services:
  app:
    build: .
    environment:
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/password
    secrets:
      - source: database-password
        target: /run/secrets/password
```
and the following `META-INF/spring.factories`:
```ini
org.springframework.boot.env.EnvironmentPostProcessor=\
  de.vinado.boot.secrets.EnvironmentSecretsPropertyEnvironmentPostProcessor
```

with no additional configuration specified, I would have expected to end up with `spring.datasource.password=foo`. It remains unset, however.

For the time being, I resorted to enabling all post processors and rely on implicit files below `/run/secrets`, which works; but actually being able to set `_FILE` variables would be great.
